CREATE TABLE IF NOT EXISTS public.lm_feedback_intake (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_ref text NOT NULL,
  summary text NOT NULL CHECK (char_length(summary) BETWEEN 1 AND 500),
  labels text[] NOT NULL CHECK (cardinality(labels) BETWEEN 1 AND 8),
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'issued')),
  issue_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_ref)
);

CREATE INDEX IF NOT EXISTS lm_feedback_intake_status_created_idx
  ON public.lm_feedback_intake (status, created_at);

REVOKE ALL ON TABLE public.lm_feedback_intake FROM PUBLIC;
REVOKE ALL ON SEQUENCE public.lm_feedback_intake_id_seq FROM PUBLIC;
