#!/usr/bin/env python3
"""CANONICAL SHARED POSTER — 全 marketing loop（clip / capafy / 将来の affiliate 等）が --handle で account を渡して共有。account 名を焼かない。web composer は dead-end につき廃止。"""
# instagrapi-based IG Reel/carousel poster — the VERIFIED FREE posting method (2026-07-14), replaces the
# web-composer post_reel.py which was a structural dead end (IG silently drops automated web posts).
# Flow: pull the CloakBrowser's already-logged-in sessionid (avoids a fresh-login challenge) ->
# instagrapi.login_by_sessionid -> clip_upload (reel) or album_upload (carousel) ->
# verify reels are publicly visible. Prints ONE structured JSON line matching run.sh's contract
# ({"outcome": "published"|"failed"|"dry", "post_url": ..., "before_hrefs": []}).
#
# ★ SESSION POLICY (SSOT: docs/earn/ig-4account-reels-carousel-loop-plan.md v22/v23/v24) ★
# v23's core finding: the FIRST login after signup ("golden session") passes cleanly. Once that
# session dies, a password relogin ALWAYS trips bloks ChallengeRequired and semi-poisons the
# account. So the only thing that matters is: never let the golden session die, and never relogin
# once it has. Concretely (copy-sourced from alsk1992/instagram-ai-agent + subzeroid/instagrapi,
# v24):
#   1. tier1 (gold standard) = load_settings() + a read-only verification call. NEVER falls
#      through to password login while a saved session exists — even if it looks dead, a plain
#      LoginRequired is not a green light to relogin (only a genuinely fresh account, with NO
#      settings file at all, is allowed to take the tier3 path). copy=ig.py L556-708.
#   2. tier2 (browser sessionid) is skipped entirely for accounts with session_owner=="instagrapi"
#      in clip-accounts.json (v22: a parallel browser session is what kills the golden session via
#      churn in the first place).
#   3. tier3 (password login) fires ONLY when instagrapi-<handle>.json has never existed, gated by
#      a 24h cooldown stamp, and never generates a second attempt.
#   4. A bloks ChallengeRequired at ANY tier quarantines the account. We do not retry private-API
#      login. A separately authorized browser flow may clear the provider warning; only an exact
#      account_info identity plus feed+launcher proof may atomically promote the row again.
#   5. Device uuids are never freshly generated by this module — the only path that sets them is
#      load_settings()->set_settings()->init(), which restores the uuids already saved in the
#      settings file. We never call cl.set_uuids() with newly generated values.
import argparse, datetime, json, os, sys, re, time, subprocess, urllib.request
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)
from instagram_credentials import credential_password  # noqa: E402
from websocket import create_connection  # noqa: E402
from instagrapi.exceptions import ChallengeRequired, LoginRequired  # noqa: E402

C = os.path.expanduser


def page_ws(target_id, port):
    """Return the page CDP endpoint without relying on a home-directory adapter."""
    host = os.environ.get("CDP_HOST", "localhost")
    return f"ws://{host}:{port}/devtools/page/{target_id}"


def cdp_http_url(port, path):
    """Return a browser HTTP endpoint for local or private-cloud CDP."""
    host = os.environ.get("CDP_HOST", "localhost")
    return f"http://{host}:{port}{path}"


def make_gmail_handler(handle, credentials_path=None):
    # instagrapi calls this on an email challenge; auto-read the 6-digit code from the
    # account's gmail plus-address inbox via `gog gmail`. Never prints the code.
    def handler(username=None, choice=None):
        path = credentials_path or C(f"~/.cloak/ig-{handle}.json")
        with open(path, encoding="utf-8") as source:
            creds = json.load(source)
        base = creds["email"].split("+")[0] + "@gmail.com"
        end = time.time() + 180
        while time.time() < end:
            out = subprocess.run(
                ["gog", "gmail", "search", "from:instagram newer_than:1h", "-j",
                 "--results-only", "-a", base],
                capture_output=True, text=True)
            try:
                threads = json.loads(out.stdout) or []
            except Exception:
                threads = []
            for t in threads:
                body = subprocess.run(
                    ["gog", "gmail", "get", t.get("id"), "-j", "--results-only", "-a", base],
                    capture_output=True, text=True).stdout
                g = re.search(r"(?<!\d)(\d{6})(?!\d)", t.get("subject", "") + " " + body)
                if g:
                    return g.group(1)
            time.sleep(10)
        raise Exception("no gmail challenge code within 180s")
    return handler


def logout_reason(cl):
    # Diagnostic ONLY — never raises. When IG kills a session it may set last_response's
    # `logout_reason` to signature_revoked / password_changed / concurrent_session; capturing it is
    # the single cheapest way to confirm WHY a session died (per instagrapi.com/guides/errors/
    # login-required). Read-only: does not touch the login flow. Returns "" when unavailable.
    try:
        lr = cl.last_response.json()
        return lr.get("logout_reason") or lr.get("message") or ""
    except Exception:
        return ""


def is_bloks_challenge(e):
    # A bloks native ChallengeRequired quarantines private-API use. A plain
    # LoginRequired/TooManyRedirects is only a dead-session signal.
    return isinstance(e, ChallengeRequired)


def authenticated_handle(cl):
    account = cl.account_info()
    username = getattr(account, "username", None)
    if username is None and isinstance(account, dict):
        username = account.get("username")
    return username if isinstance(username, str) else ""


def account_session_owner(handle, accounts_path=None):
    # v22: some accounts are flagged session_owner="instagrapi" — a parallel browser session
    # (tier2) is what causes session churn on those accounts, so tier2 must be skipped for them.
    accounts_path = accounts_path or C("~/.cloak/clip-accounts.json")
    try:
        with open(accounts_path, encoding="utf-8") as source:
            accounts = json.load(source)
    except Exception:
        return None
    for a in accounts:
        if a.get("handle") == handle:
            return a.get("session_owner")
    return None


def mark_poisoned(handle, reason, accounts_path=None):
    # A provider ChallengeRequired quarantines the row. Private-API relogin stays forbidden; an
    # exact browser-authorized identity proof may later recover this same account.
    accounts_path = accounts_path or C("~/.cloak/clip-accounts.json")
    try:
        with open(accounts_path, encoding="utf-8") as source:
            accounts = json.load(source)
    except Exception:
        return False
    changed = False
    for a in accounts:
        if a.get("handle") == handle:
            a["status"] = "poisoned_manual_backup"
            a["poisoned_reason"] = reason
            a["poisoned_at"] = time.strftime("%Y-%m-%dT%H:%MZ", time.gmtime())
            changed = True
    if changed:
        with open(accounts_path, "w") as f:
            json.dump(accounts, f, indent=2, ensure_ascii=False)
    return changed


def recover_verified_account(handle, accounts_path=None):
    """Atomically promote only the exact poisoned row after provider identity proof."""
    accounts_path = accounts_path or C("~/.cloak/clip-accounts.json")
    if os.path.islink(accounts_path):
        return False
    try:
        with open(accounts_path, encoding="utf-8") as source:
            accounts = json.load(source)
    except Exception:
        return False
    if not isinstance(accounts, list):
        return False
    matches = [account for account in accounts if account.get("handle") == handle]
    if len(matches) != 1 or matches[0].get("status") != "poisoned_manual_backup":
        return False
    account = matches[0]
    account["status"] = "ready"
    account["session_owner"] = "instagrapi"
    account["recovered_at"] = datetime.datetime.now(
        datetime.timezone.utc
    ).isoformat().replace("+00:00", "Z")
    account.pop("poisoned_reason", None)
    account.pop("poisoned_at", None)
    temporary = f"{accounts_path}.tmp-{os.getpid()}"
    try:
        descriptor = os.open(
            temporary,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o600,
        )
        with os.fdopen(descriptor, "w", encoding="utf-8") as output:
            json.dump(accounts, output, indent=2, ensure_ascii=False)
            output.write("\n")
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary, accounts_path)
        os.chmod(accounts_path, 0o600)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
    return True


def keepalive(cl):
    # Read-only session-alive probe (v24 point 2). Never writes, never relogins. Returns False
    # ONLY on a confirmed LoginRequired (the session is actually dead); any other exception is
    # treated as an inconclusive/transient blip, not proof of death, so it must NOT trigger a
    # relogin attempt elsewhere in the pipeline. A bloks ChallengeRequired is neither of those —
    # it means the account is poisoned, so it must propagate to the caller (keepalive_main),
    # never be swallowed as "alive" (v24 #12).
    try:
        cl.get_timeline_feed()
        return True
    except LoginRequired:
        return False
    except ChallengeRequired:
        raise
    except Exception:
        return True


def gentle_ping(cl):
    # Second, even-lighter keepalive probe: instagrapi's own launcher/sync/ private endpoint — the
    # same idle-refresh call the real IG app fires on cold start — used by long-lived-session IG
    # bots to keep server-side trust warm without a full feed read.
    # copy=alsk1992/instagram-ai-agent plugins/ig.py L1142-1250 (two-stage keepalive: feed probe +
    # launcher/sync ping). instagrapi exposes the same endpoint as Client.sync_launcher(); if a
    # future instagrapi version drops it, fall back to keepalive()'s get_timeline_feed read.
    try:
        cl.sync_launcher(login=False)
        return True
    except LoginRequired:
        return False
    except ChallengeRequired:
        raise
    except AttributeError:
        return keepalive(cl)
    except Exception:
        return True


def login_resilient(
    cl,
    handle,
    port,
    res,
    settings_path=None,
    accounts_path=None,
    credentials_path=None,
    profile_state_dir=None,
):
    # Self-healing login so the loop never needs a human to log in again. Order matters (v22/v23/
    # v24 — see module docstring):
    #   1) reuse the saved instagrapi session (device+cookies) — the "golden session". NEVER falls
    #      through to password login while this tier is available.
    #   2) fall back to the browser's live sessionid — but ONLY for accounts NOT owned by
    #      instagrapi (session_owner flag), since a parallel browser session is the churn vector.
    #   3) fall back to a full password login — but ONLY for an account that has NEVER had a saved
    #      instagrapi session (settings file truly absent). One attempt, 24h cooldown.
    settings = settings_path or C(f"~/.cloak/instagrapi-{handle}.json")
    accounts_path = accounts_path or C("~/.cloak/clip-accounts.json")
    try:
        with open(accounts_path, encoding="utf-8") as source:
            account = next(
                a for a in json.load(source) if a.get("handle") == handle
            )
        started = account.get("started_warming") or account.get("created")
        age = (datetime.date.today() - datetime.date.fromisoformat(started)).days + 1
    except Exception:
        age = None
    if age is not None and age < 3:
        res["error"] = f"instagrapi login refused: warming_day={age} < 3"
        res["refused"] = "warming_day<3"
        return False
    settings_existed = os.path.exists(settings)

    if settings_existed:
        try:
            cl.load_settings(settings)
            cl.get_timeline_feed()
            if authenticated_handle(cl).casefold() != handle.casefold():
                res["error"] = "authenticated Instagram identity mismatch"
                return False
            cl.dump_settings(settings)  # persist server-rotated cookies (gold standard, alsk1992 ig.py L556-708)
            return True
        except Exception as e:
            reason = logout_reason(cl)
            res["tier1_dead"] = f"{type(e).__name__}: {reason}"
            print(f"login_resilient tier1 (saved session) dead: {type(e).__name__} logout_reason={reason!r}", file=sys.stderr)
            if is_bloks_challenge(e):
                mark_poisoned(handle, f"tier1 load_settings ChallengeRequired: {reason}", accounts_path)
                res["poisoned"] = True
                res["error"] = "account quarantined after ChallengeRequired; browser authorization is required, private-API relogin is forbidden"
                return False

    if account_session_owner(handle, accounts_path) != "instagrapi":
        try:
            _, sid = get_sessionid(port)
            if sid:
                cl.login_by_sessionid(sid)
                if cl.username == handle:
                    cl.dump_settings(settings)
                    return True
        except Exception as e:
            reason = logout_reason(cl)
            res["tier2_dead"] = f"{type(e).__name__}: {reason}"
            print(f"login_resilient tier2 (browser sessionid) dead: {type(e).__name__} logout_reason={reason!r}", file=sys.stderr)
            if is_bloks_challenge(e):
                mark_poisoned(handle, f"tier2 login_by_sessionid ChallengeRequired: {reason}", accounts_path)
                res["poisoned"] = True
                res["error"] = "account quarantined after ChallengeRequired; browser authorization is required, private-API relogin is forbidden"
                return False
    else:
        res["tier2_skipped"] = "session_owner=instagrapi — browser session forbidden for this account (v22 churn guard)"

    if settings_existed:
        # ★ RELOGIN REFUSAL (v23 core finding): a saved session that died is NOT a green light to
        # password-login. Relogin on a previously-alive session is exactly what trips bloks and
        # semi-poisons the account. Refuse until browser authorization plus exact identity proof. ★
        res["error"] = "saved session dead and no fresh-account exemption applies — refusing relogin through the private API; browser authorization is required."
        return False

    try:
        # ★ TIER3 COOLDOWN GUARD (TASKLIST 3a): repeated password logins are a STOP signal to IG —
        # each attempt deepens distrust and triggers session revocation / reCAPTCHA Enterprise.
        # Observed 2026-07-16: two tier3 logins within minutes both "succeeded" then got revoked
        # mid-use (LoginRequired during clip_upload). At most ONE password attempt per 24h, and
        # only for an account that has never had a saved session (settings_existed is False here).
        stamp = os.path.join(
            profile_state_dir or C("~/.cloak"),
            f".last-pwlogin-{handle}",
        )
        last = os.path.getmtime(stamp) if os.path.exists(stamp) else 0
        if time.time() - last < 24 * 3600:
            res["error"] = "tier3 password login on 24h cooldown — refusing to hammer IG login (3a)"
            return False
        with open(stamp, "w", encoding="utf-8") as output:
            output.write(str(int(time.time())))  # stamp BEFORE the attempt: failures count too
        with open(
            credentials_path or C(f"~/.cloak/ig-{handle}.json"),
            encoding="utf-8",
        ) as source:
            creds = json.load(source)
        cl.login(creds["username"], credential_password(creds))
        cl.dump_settings(settings)
        return True
    except Exception as e:
        reason = logout_reason(cl)
        if is_bloks_challenge(e):
            mark_poisoned(handle, f"tier3 login ChallengeRequired: {reason}", accounts_path)
            res["poisoned"] = True
            res["error"] = "account quarantined after ChallengeRequired; browser authorization is required before any retry"
            return False
        res["error"] = f"all login paths failed: {type(e).__name__}: {str(e)[:200]}"
        return False


def account_proxy_url(handle, accounts_path=None):
    # Return this account's assigned residential/mobile proxy URL (or None for direct IP).
    # The clip-accounts.json entry carries proxy:"~/.cloak/proxy-clip-1.json". A clean, STABLE
    # per-account exit IP is the #1 anti-ban lever — a shared/datacenter IP is the documented #1
    # cause of bloks ChallengeRequired / BadPassword (docs/earn/ig-account-scale-best-practices.md).
    accounts_path = accounts_path or C("~/.cloak/clip-accounts.json")
    ppath = None
    try:
        with open(accounts_path, encoding="utf-8") as source:
            accounts = json.load(source)
        for a in accounts:
            if a.get("handle") == handle:
                ppath = a.get("proxy"); break
    except Exception:
        return None
    if not ppath:
        return None
    try:
        with open(C(ppath), encoding="utf-8") as source:
            d = json.load(source)
        return f"http://{d['username']}:{d['password']}@{d['host']}:{d['port']}"
    except Exception:
        return None


def apply_proxy(cl, handle, res=None, accounts_path=None):
    # Route ALL instagrapi traffic for this account through its assigned residential/mobile proxy so
    # IG always sees ONE consistent, non-datacenter exit IP. Never echoes the proxy URL/creds.
    url = account_proxy_url(handle, accounts_path)
    if url:
        cl.set_proxy(url)
        if res is not None:
            res["proxy"] = "residential (assigned)"
        return True
    if res is not None:
        res["proxy"] = "none (direct IP)"
    return False


def keepalive_main(handle, settings_path=None, accounts_path=None, client_factory=None):
    # v24 point 2, wired: two-stage read-only probe on the golden session, fired by
    # session_vault_tick.sh every 30 min so the session never rots between posts.
    # NEVER logs in. Browser authorization is the only recovery path for a quarantined account.
    # On success, persist refreshed cookies back to disk (gold standard: alsk1992 ig.py L556-708).
    res = {
        "handle": handle,
        "mode": "keepalive",
        "alive": False,
        "identity_ok": False,
        "recovered": False,
    }
    settings = settings_path or C(f"~/.cloak/instagrapi-{handle}.json")
    if not os.path.exists(settings):
        res["error"] = "no saved session — keepalive only applies to accounts with a golden session"
        return res
    if client_factory is None:
        from instagrapi import Client
        client_factory = Client
    cl = client_factory()
    cl.delay_range = [1, 3]
    apply_proxy(cl, handle, res, accounts_path)
    try:
        cl.load_settings(settings)
    except Exception as e:
        res["error"] = f"load_settings failed: {type(e).__name__}"
        return res
    try:
        res["feed_ok"] = keepalive(cl)
        res["ping_ok"] = gentle_ping(cl) if res["feed_ok"] else False
        if res["feed_ok"] and res["ping_ok"]:
            res["identity_ok"] = (
                authenticated_handle(cl).casefold() == handle.casefold()
            )
        res["alive"] = bool(
            res["feed_ok"] and res["ping_ok"] and res["identity_ok"]
        )
        if res["alive"]:
            cl.dump_settings(settings)
            res["recovered"] = recover_verified_account(handle, accounts_path)
        elif res["feed_ok"] and res["ping_ok"]:
            res["error"] = "authenticated Instagram identity mismatch"
    except ChallengeRequired:
        mark_poisoned(handle, "keepalive ChallengeRequired (bloks) — browser authorization required; never private-API relogin", accounts_path)
        res["poisoned"] = True
        res["error"] = "account quarantined after ChallengeRequired during keepalive"
    return res


def verify_only_main(
    handle,
    port,
    settings_path=None,
    accounts_path=None,
    credentials_path=None,
    profile_state_dir=None,
    client_factory=None,
):
    # SHARED-1 (INV-3): read-only replacement for post_reel.py's browser-DOM --verify-only mode —
    # returns the account's current reel/post hrefs via the instagrapi private API (no browser DOM
    # read needed). Used by self_heal.py and earn/video/run.sh to reconcile a possibly-landed post
    # without risking a double-post. NEVER posts; the shape ({"ok", "reels"}) matches what those two
    # callers already parse from the old post_reel.py verify-only JSON.
    res = {"handle": handle, "verify_only": True, "ok": False, "reels": []}
    if client_factory is None:
        from instagrapi import Client
        client_factory = Client
    cl = client_factory()
    cl.delay_range = [1, 3]
    apply_proxy(cl, handle, res, accounts_path)
    cl.challenge_code_handler = make_gmail_handler(handle, credentials_path)
    if not login_resilient(
        cl,
        handle,
        port,
        res,
        settings_path,
        accounts_path,
        credentials_path,
        profile_state_dir,
    ):
        return res
    try:
        medias = cl.user_medias(cl.user_id, amount=12)
        reels = []
        for m in medias:
            d = m.model_dump() if hasattr(m, "model_dump") else m.dict()
            code = d.get("code")
            if not code:
                continue
            kind = "reel" if d.get("product_type") == "clips" else "p"
            reels.append(f"/{handle}/{kind}/{code}/")
        res["reels"] = reels
        res["ok"] = True
    except Exception as e:
        res["error"] = f"{type(e).__name__}: {str(e)[:200]}"
    return res


def get_sessionid(port):
    tabs = json.load(urllib.request.urlopen(cdp_http_url(port, "/json/list")))
    tid = next(t["id"] for t in tabs if t.get("type") == "page" and "instagram.com" in (t.get("url") or ""))
    ws = create_connection(page_ws(tid, port), timeout=20, suppress_origin=True, max_size=None)
    ws.send(json.dumps({"id": 1, "method": "Network.enable"}))
    ws.send(json.dumps({"id": 2, "method": "Network.getAllCookies"}))
    sid = None
    end = time.time() + 15
    while time.time() < end:
        m = json.loads(ws.recv())
        if m.get("id") == 2:
            for c in m["result"]["cookies"]:
                if c["name"] == "sessionid" and "instagram" in c["domain"]:
                    sid = c["value"]
            break
    ws.close()
    return tid, sid


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--video")
    ap.add_argument("--images", help="comma-separated image paths for a 2-10 image carousel")
    ap.add_argument("--caption-file")
    ap.add_argument("--handle", required=True)
    ap.add_argument("--port", default=os.environ.get("CDP_PORT", "9222"))
    ap.add_argument("--accounts-path", help="account state JSON; defaults to ~/.cloak/clip-accounts.json")
    ap.add_argument("--settings-path", help="saved instagrapi session supplied by the tenant profile")
    ap.add_argument("--credentials-path", help="tenant-scoped Instagram credential record")
    ap.add_argument("--profile-state-dir", help="tenant-scoped mutable Instagram profile state")
    ap.add_argument("--live", action="store_true")
    ap.add_argument("--keepalive", action="store_true",
                     help="read-only golden-session probe; no post, never logs in")
    ap.add_argument("--verify-only", action="store_true",
                     help="read-only: return the account's current reel/post hrefs; no posting (SHARED-1 INV-3)")
    a = ap.parse_args()
    accounts_path = a.accounts_path or C("~/.cloak/clip-accounts.json")
    if a.keepalive:
        print(json.dumps(keepalive_main(
            a.handle,
            settings_path=a.settings_path,
            accounts_path=accounts_path,
        ), ensure_ascii=False)); return
    if a.verify_only:
        print(json.dumps(verify_only_main(
            a.handle,
            a.port,
            settings_path=a.settings_path,
            accounts_path=accounts_path,
            credentials_path=a.credentials_path,
            profile_state_dir=a.profile_state_dir,
        ), ensure_ascii=False)); return
    # ★ FREEZE GATE (fail-closed for posting; Dais 2026-07-17 "1 loop = 1 acc" ruling): a handle whose
    #   supplied account-state status starts with "frozen" must never be POSTED to from ANY path -- the
    #   production run.sh chain and one-off diagnostic scripts alike (pass45's post_reel_diag.py posted
    #   a real reel to frozen @aiclips_studio_hq precisely because no chokepoint enforced the freeze).
    #   Read-only modes (--keepalive/--verify-only) return above and stay allowed ("Data kept, NOT deleted").
    try:
        with open(accounts_path, encoding="utf-8") as source:
            _accts = json.load(source)
        _frozen_status = next((x.get("status") for x in _accts if x.get("handle") == a.handle), None)
    except Exception:
        _frozen_status = None  # no ledger -> no freeze info; never invent a block for unlisted handles
    if _frozen_status and str(_frozen_status).startswith("frozen"):
        print(json.dumps({"handle": a.handle, "outcome": "refused_frozen_account", "post_url": None,
                          "note": "account state status=%s; posting on this handle is disabled by the freeze policy" % _frozen_status},
                         ensure_ascii=False))
        return
    if bool(a.video) == bool(a.images):
        ap.error("exactly one of --video or --images is required unless --keepalive/--verify-only")
    if not a.caption_file:
        ap.error("--caption-file is required unless --keepalive/--verify-only")
    image_paths = [path.strip() for path in a.images.split(",") if path.strip()] if a.images else []
    if a.images and not 2 <= len(image_paths) <= 10:
        ap.error("--images requires 2-10 comma-separated paths")
    res = {"handle": a.handle, "outcome": "failed", "post_url": None, "before_hrefs": []}
    try:
        with open(a.caption_file, encoding="utf-8") as source:
            caption = source.read().strip()

        from instagrapi import Client
        cl = Client()
        cl.delay_range = [1, 3]
        apply_proxy(cl, a.handle, res, accounts_path)
        cl.challenge_code_handler = make_gmail_handler(a.handle, a.credentials_path)
        # ★ ACCOUNT GUARD (fail-closed): the session is loaded from instagrapi-<handle>.json (tier 1/3)
        #   or verified cl.username==handle (tier 2), so we can only ever act as the right account. ★
        if not login_resilient(
            cl,
            a.handle,
            a.port,
            res,
            settings_path=a.settings_path,
            accounts_path=accounts_path,
            credentials_path=a.credentials_path,
            profile_state_dir=a.profile_state_dir,
        ):
            print(json.dumps(res, ensure_ascii=False)); return

        if not a.live:
            res["outcome"] = "dry"; res["reached"] = "login-ok"
            print(json.dumps(res, ensure_ascii=False)); return

        if a.video:
            thumb = a.video + ".jpg"
            subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", a.video, "-ss", "1", "-vframes", "1", thumb], check=True)
            media = cl.clip_upload(a.video, caption, thumbnail=thumb)
        else:
            media = cl.album_upload(image_paths, caption)
        d = media.model_dump() if hasattr(media, "model_dump") else media.dict()
        code = d.get("code")
        url = f"https://www.instagram.com/{'reel' if a.video else 'p'}/{code}/"

        # REALITY GATE: confirm the reel is publicly visible (logged-out) before claiming success.
        public = None
        if a.video:
            time.sleep(3)
            try:
                req = urllib.request.Request(f"https://www.instagram.com/{a.handle}/", headers={"User-Agent": "Mozilla/5.0"})
                html = urllib.request.urlopen(req, timeout=12).read().decode("utf-8", "ignore")
                public = bool(code) and code in html
            except Exception:
                public = None  # network gate; instagrapi's returned code is still the source of truth

        res["outcome"] = "published"; res["post_url"] = url; res["code"] = code
        res["public_verified"] = public; res["reached"] = "PUBLISHED"
    except Exception as e:
        res["error"] = f"{type(e).__name__}: {str(e)[:300]}"
    print(json.dumps(res, ensure_ascii=False))


if __name__ == "__main__":
    main()
