import { privateKeyToAccount } from "viem/accounts";
import { readFileSync } from "node:fs";
const w=JSON.parse(readFileSync(process.env.HOME+"/.anicca-founder/wallet.json","utf8"));
let pk=w.private_key.startsWith("0x")?w.private_key:"0x"+w.private_key;
const acct=privateKeyToAccount(pk);const API="https://api.bountybook.ai";
const n=await(await fetch(`${API}/auth/nonce?address=${acct.address}`)).json();
const sig=await acct.signMessage({message:String(n.nonce||n.message||n)});
const v=await(await fetch(`${API}/auth/verify`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({address:acct.address,signature:sig})})).json();
const j=await(await fetch(`${API}/jobs/${process.argv[2]}`,{headers:{Authorization:"Bearer "+v.token}})).json();
console.log(JSON.stringify(j.job||j,null,1).slice(0,1500));
