# slideshow marketing loop manifest — the ONLY per-loop config. Engine is SHARED in ../ .
# LANE: agent-owned — single lane, Postiz cancelled 2026-07. Amazon tag aniccaai-22 は Dais 資産のため live 前に agent 自己所有の収益先へ置換必須。LIVE 発火は #30 day3 実証後
# Generated by spawn-marketing-loop.sh from a free-text product description.
#
#   WHO (persona) · WHAT PROBLEM · WHAT you sell (product) · HOW (content adapter)

# ── WHO / WHAT PROBLEM ──
MKT_PERSONA="Amazon shoppers looking for practical product recommendations"
MKT_PROBLEM="Comparing products takes too much time and research"

# ── WHAT you sell (product) ──
MKT_INSTANCE="slideshow"
MKT_PRODUCT_SOURCE="Amazon affiliate product recommendations using Dais asset tag aniccaai-22"
MKT_LISTING_URL_FMT=""
MKT_BIO_LINK="https://example.com/amazon-affiliate-landing"
MKT_LANDING_SITE_ID=""

# ── HOW (content) ──
MKT_CONTENT_ADAPTER="slideshow"          # faceless-video | slideshow | carousel | clip-cut
MKT_NICHE="amazon-product-guides"

# ── account / provision (fed to shared provision_prompt.sh) ──
MKT_ACCOUNT_STATE_FILE="$HOME/.cloak/marketing-accounts-slideshow.json"
MKT_HANDLE_PREFIX="slideshow"
MKT_PROFILE_PREFIX="slideshow-mkt"
MKT_GMAIL_PLUS_TAG_PREFIX="slideshow"
MKT_BIO_TEXT="Quick visual guides to products worth considering"

# ── cadence ──
MKT_CADENCE_HOUR="16"                          # daily launchd hour (JST)
