#!/usr/bin/env bash
# run-daily.sh <script_file> [en] — the DETERMINISTIC tail of the factory.
# AI-AGNOSTIC BY DESIGN: this script contains NO LLM call, NO provider, NO model name. The AGENT
# running this skill (whatever it is — DeepSeek on OpenClaw, Claude, anything) writes the fresh
# script ITSELF in natural language per SKILL.md, saves it to <script_file>, then calls this to turn
# that text into the finished faceless video + DRAFT. Any AI on earth can run it.
#
# Steps (all $0, keyless): free TTS (edge-tts) → free b-roll (Mixkit) → beat-aligned assemble +
# burned captions → DRAFT email for approval (DRAFT_ONLY=1, default) or post (DRAFT_ONLY=0).
set -uo pipefail
SCRIPT_FILE="${1:?script_file required — the agent writes the fresh script first (see SKILL.md)}"
LANG_CODE="${2:-en}"
DRAFT_ONLY="${DRAFT_ONLY:-1}"
export PATH="$HOME/.local/bin:$PATH"
_AH="${ANICCA_HOME:-}"; set -a; [ -f "$HOME/.hermes/.env" ] && . "$HOME/.hermes/.env"; [ -f "$HOME/.local/state/rockstar_ibot/.env" ] && . "$HOME/.local/state/rockstar_ibot/.env"; [ -n "$_AH" ] && ANICCA_HOME="$_AH"; unset _AH; set +a   # for edge-tts proxy / gog keyring only
: "${GOG_KEYRING_PASSWORD:?GOG_KEYRING_PASSWORD is required}"
export GOG_KEYRING_PASSWORD
SK="$HOME/.claude/skills/faceless-money-factory"; S="$SK/scripts"
[ -d "$S" ] || SK="$(cd "$(dirname "$0")/.." && pwd)"; S="$SK/scripts"
OUT="$SK/state/renders"; mkdir -p "$OUT"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

[ -s "$SCRIPT_FILE" ] || { echo "EMPTY_SCRIPT ($SCRIPT_FILE)" >&2; exit 2; }
SCRIPT="$(cat "$SCRIPT_FILE")"
ID="money-$(date +%Y%m%d-%H%M%S)"
# b-roll search query = simple keyword PARSE of the script (deterministic, not judgment)
# BROLL_QUERY env lets a non-finance caller (e.g. the Capafy IG loop) pick topic-appropriate
# b-roll instead of the finance default — the running agent sets it per the listing's category.
QUERY="${BROLL_QUERY:-$(printf '%s' "$SCRIPT" | tr 'A-Z' 'a-z' | grep -oE 'money|saving|invest|budget|debt|credit|retire|tax|income|wealth|stock|bank' | head -1)}"; [ -n "$QUERY" ] || QUERY="money"
echo "id=$ID query=$QUERY chars=${#SCRIPT}"
printf '%s\n' "$SCRIPT" > "$OUT/$ID.script.txt"

echo "=== [1] TTS (edge-tts, free, keyless) ==="
edge-tts --voice "${MONEY_EN_VOICE:-en-US-AndrewNeural}" --rate=+8% --text "$SCRIPT" --write-media "$WORK/voice.mp3" 2>/dev/null
[ -s "$WORK/voice.mp3" ] || { echo "TTS_FAILED" >&2; exit 3; }

echo "=== [2] b-roll (Mixkit free + library fallback) ==="
bash "$S/fetch-broll.sh" "$QUERY" "$WORK/broll" 8

echo "=== [3] assemble (beat-aligned + captions) ==="
bash "$S/assemble.sh" "$WORK/voice.mp3" "$WORK/broll" "$OUT/$ID.mp4" "$LANG_CODE"

VDUR=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$OUT/$ID.mp4" 2>/dev/null || echo 0)
HASA=$(ffprobe -v error -select_streams a -show_entries stream=codec_type -of csv=p=0 "$OUT/$ID.mp4" 2>/dev/null | head -1)
echo "render: dur=${VDUR}s audio=${HASA:-NONE}"
[ "${HASA:-}" = "audio" ] || { echo "RENDER_BAD" >&2; exit 6; }

if [ "$DRAFT_ONLY" = "1" ]; then
  echo "=== [4] DRAFT email (approval gate) ==="
  BODY="$(printf 'Daily faceless money short (AI-generated by this agent, $0, DRAFT — not posted).\n\nID: %s\nDuration: %ss\n\nScript:\n%s\n' "$ID" "$VDUR" "$SCRIPT")"
  GMAIL_ACCOUNT="${GOG_ACCOUNT:-}"
  if [ -n "$GMAIL_ACCOUNT" ]; then
    gog gmail send --account "$GMAIL_ACCOUNT" --to "$GMAIL_ACCOUNT" \
      --subject "💸 Daily money short DRAFT — $ID" --body "$BODY" --attach "$OUT/$ID.mp4" 2>&1 | tail -2
  else
    echo "DRAFT_EMAIL_SKIPPED GOG_ACCOUNT unset"
  fi
else
  echo "=== [4] POST (accounts wired) — poster step (YT/TikTok/IG) ==="
fi
echo "RUN_DONE id=$ID file=$OUT/$ID.mp4 draft_only=$DRAFT_ONLY"
