#!/usr/bin/env python3
"""Build and stage one immutable self-owned paid Writer article."""

from __future__ import annotations

import hashlib
import html
import json
import os
import re
import subprocess
import argparse
import urllib.request
import fcntl
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse


class SelfOwnedInvariant(ValueError):
    """The frozen article, target repository, or public receipt is unsafe."""


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _without_frontmatter(markdown: str) -> str:
    value = markdown.replace("\r\n", "\n").strip()
    if value.startswith("---\n"):
        end = value.find("\n---\n", 4)
        if end < 0:
            raise SelfOwnedInvariant("frontmatter is unterminated")
        value = value[end + 5 :].lstrip()
    return value


def _visible_chars(value: str) -> int:
    text = re.sub(r"!\[[^]]*\]\([^)]+\)", "", value)
    text = re.sub(r"\[([^]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"[`#>*_~-]", "", text)
    return len(re.sub(r"\s+", "", text))


def _title(markdown: str) -> str:
    match = re.search(r"(?m)^#\s+(.+?)\s*$", markdown)
    if not match:
        raise SelfOwnedInvariant("article requires one H1 title")
    return match.group(1).strip()


def _slug(title: str, lang: str, source: str) -> str:
    ascii_title = title.encode("ascii", "ignore").decode("ascii").lower()
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_title).strip("-")
    if not slug:
        slug = f"writer-{lang}-{sha256_text(source)[:12]}"
    return slug[:100].rstrip("-")


def build_contract(
    *, run_id: str, lang: str, markdown: str, after_chars: int = 1200,
    minimum_preview_chars: int = 1000,
) -> dict:
    if not re.fullmatch(r"[A-Za-z0-9._-]{4,100}", run_id or ""):
        raise SelfOwnedInvariant("run_id is invalid")
    if lang not in {"ja", "en"}:
        raise SelfOwnedInvariant("language is unsupported")
    source = _without_frontmatter(markdown)
    boundary = None
    for match in re.finditer(r"(?m)^##\s+.+$", source):
        visible = _visible_chars(source[: match.start()])
        if visible >= after_chars and visible >= minimum_preview_chars:
            boundary = match.start()
            break
    if boundary is None:
        raise SelfOwnedInvariant("no useful paid-section boundary after public preview")
    preview = source[:boundary].rstrip()
    paid = source[boundary:].strip()
    if _visible_chars(preview) < minimum_preview_chars or not paid:
        raise SelfOwnedInvariant("public preview or paid body is insufficient")
    canonical = f"{preview}\n\n{paid}"
    title = _title(source)
    return {
        "slug": _slug(title, lang, canonical),
        "run_id": run_id,
        "artifact_id": f"{run_id}__self-owned__{lang}",
        "lang": lang,
        "title": title,
        "source_sha256": sha256_text(canonical),
        "preview_markdown": preview,
        "preview_sha256": sha256_text(preview),
        "paid_markdown": paid,
        "paid_sha256": sha256_text(paid),
        "access_model": "both",
    }


def _git(root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=root, text=True, capture_output=True, check=False,
    )
    if result.returncode != 0:
        raise SelfOwnedInvariant(result.stderr.strip() or "git command failed")
    return result.stdout.strip()


def stage_contract(landing_root: Path, contract: dict) -> dict:
    return stage_contracts(landing_root, [contract])[0]


def _contract_target(root: Path, contract: dict) -> tuple[Path, Path, str]:
    slug = contract.get("slug")
    if not isinstance(slug, str) or re.fullmatch(r"[a-z0-9][a-z0-9-]{0,99}", slug) is None:
        raise SelfOwnedInvariant("contract slug is invalid")
    relative = Path("apps/landing/private/writer-articles") / f"{slug}.json"
    encoded = json.dumps(contract, ensure_ascii=False, indent=2) + "\n"
    return relative, root / relative, encoded


REGISTRY_RELATIVE = Path(
    "apps/landing/netlify/functions/_lib/writer-article-registry.generated.js"
)


def _registry_source(slugs: list[str]) -> str:
    rows = "\n".join(
        f"  '{slug}': require('../../../private/writer-articles/{slug}.json'),"
        for slug in sorted(slugs)
    )
    return (
        "// Generated by the Writer publication adapter. Keep every require static so\n"
        "// Netlify bundles paid contracts even when included_files is not mounted.\n"
        "const articles = Object.freeze({\n"
        f"{rows}\n"
        "});\n\n"
        "function bundledWriterArticle(slug) {\n"
        "  return Object.hasOwn(articles, slug) ? articles[slug] : null;\n"
        "}\n\n"
        "module.exports = { bundledWriterArticle };\n"
    )


def _all_contract_slugs(root: Path, prepared: list[tuple[Path, Path, str]]) -> list[str]:
    article_dir = root / "apps/landing/private/writer-articles"
    slugs = {path.stem for path in article_dir.glob("*.json")}
    slugs.update(relative.stem for relative, _target, _encoded in prepared)
    if any(re.fullmatch(r"[a-z0-9][a-z0-9-]{0,99}", slug) is None for slug in slugs):
        raise SelfOwnedInvariant("existing contract slug is invalid")
    return sorted(slugs)


def stage_contracts(landing_root: Path, contracts: list[dict]) -> list[dict]:
    """Write all contracts only after the whole clean transaction validates."""
    root = Path(landing_root).resolve()
    if _git(root, "rev-parse", "--show-toplevel") != str(root):
        raise SelfOwnedInvariant("landing root is not the exact git worktree")
    status = _git(root, "status", "--porcelain", "--untracked-files=all")
    if status:
        raise SelfOwnedInvariant("landing worktree is dirty")
    if not contracts:
        raise SelfOwnedInvariant("at least one contract is required")
    prepared = [_contract_target(root, contract) for contract in contracts]
    if len({str(item[0]) for item in prepared}) != len(prepared):
        raise SelfOwnedInvariant("contracts resolve to a duplicate stable slug")
    registry_target = root / REGISTRY_RELATIVE
    registry_encoded = _registry_source(_all_contract_slugs(root, prepared))
    results = []
    for relative, target, _encoded in prepared:
        if not target.exists():
            results.append({"status": "staged", "relative_path": str(relative)})
            continue
        try:
            current = json.loads(target.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError) as error:
            raise SelfOwnedInvariant("slug conflict with unreadable target") from error
        expected = next(contract for contract in contracts if contract["slug"] == target.stem)
        if current != expected:
            raise SelfOwnedInvariant("slug conflict with different immutable bytes")
        results.append({"status": "already-present", "relative_path": str(relative)})
    registry_status = "already-present"
    try:
        if registry_target.read_text(encoding="utf-8") != registry_encoded:
            registry_status = "staged"
    except (OSError, UnicodeError):
        registry_status = "staged"
    results.append({
        "status": registry_status,
        "relative_path": str(REGISTRY_RELATIVE),
    })
    writes = [*prepared, (REGISTRY_RELATIVE, registry_target, registry_encoded)]
    for result, (_relative, target, encoded) in zip(results, writes, strict=True):
        if result["status"] == "already-present":
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        temporary = target.with_name(f".{target.name}.{os.getpid()}.tmp")
        temporary.write_text(encoded, encoding="utf-8")
        os.replace(temporary, target)
    return results


def _atomic_json(path: Path, value: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, ensure_ascii=False, separators=(",", ":"))
        handle.write("\n")
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)


class SelfOwnedPublicationStore:
    """Crash-safe adjunct state which never expands or blocks exact8."""

    def __init__(self, state_path: Path, ledger_path: Path):
        self.state_path = Path(state_path)
        self.ledger_path = Path(ledger_path)
        self.lock_path = self.state_path.with_name(f".{self.state_path.name}.lock")

    def _lock(self):
        self.lock_path.parent.mkdir(parents=True, exist_ok=True)
        lock = self.lock_path.open("a+")
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        return lock

    def _read(self) -> dict:
        try:
            value = json.loads(self.state_path.read_text(encoding="utf-8"))
        except FileNotFoundError:
            return {}
        except (OSError, UnicodeError, json.JSONDecodeError) as error:
            raise SelfOwnedInvariant("self-owned state is unreadable") from error
        if not isinstance(value, dict):
            raise SelfOwnedInvariant("self-owned state is invalid")
        return value

    def prepare(self, publication_state_path: Path, contracts: list[dict]) -> dict:
        try:
            publication = json.loads(Path(publication_state_path).read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError) as error:
            raise SelfOwnedInvariant("base publication state is unreadable") from error
        run_dir = Path(str(publication.get("run_dir", ""))).resolve()
        run_id = publication.get("run_id")
        if (
            publication.get("safety_status") != "ALLOW"
            or run_dir.name != run_id
            or set(publication.get("drafts", {})) != {"ja", "en"}
            or {item.get("lang") for item in contracts} != {"ja", "en"}
            or any(item.get("run_id") != run_id for item in contracts)
        ):
            raise SelfOwnedInvariant("base run is not safe and complete")
        for lang in ("ja", "en"):
            draft = publication["drafts"][lang]
            path = Path(str(draft.get("path", "")))
            if (
                path.resolve() != run_dir / f"article-{lang}.md"
                or not path.is_file()
                or hashlib.sha256(path.read_bytes()).hexdigest() != draft.get("sha256")
            ):
                raise SelfOwnedInvariant("frozen draft changed or moved")
        articles = {
            f"self-owned/{contract['lang']}": {
                "status": "intent",
                "target_kind": "aniccaai-slug",
                "target": contract["slug"],
                "artifact_id": contract["artifact_id"],
                "artifact_sha256": contract["source_sha256"],
                "preview_sha256": contract["preview_sha256"],
                "paid_sha256": contract["paid_sha256"],
            }
            for contract in contracts
        }
        desired = {
            "schema_version": 1,
            "run_id": run_id,
            "run_dir": str(run_dir),
            "topic_id": publication.get("topic_id"),
            "articles": articles,
        }
        with self._lock():
            current = self._read()
            if current:
                if (
                    current.get("schema_version") != 1
                    or current.get("run_id") != desired["run_id"]
                    or current.get("run_dir") != desired["run_dir"]
                    or current.get("topic_id") != desired["topic_id"]
                    or set(current.get("articles", {})) != set(articles)
                    or any(
                        {
                            key: current["articles"][pair].get(key)
                            for key in (
                                "target_kind", "target", "artifact_id",
                                "artifact_sha256", "preview_sha256", "paid_sha256",
                            )
                        }
                        != {
                            key: expected[key]
                            for key in (
                                "target_kind", "target", "artifact_id",
                                "artifact_sha256", "preview_sha256", "paid_sha256",
                            )
                        }
                        for pair, expected in articles.items()
                    )
                ):
                    raise SelfOwnedInvariant("self-owned intent conflicts with durable state")
            else:
                _atomic_json(self.state_path, desired)
            return self.plan()

    def plan(self) -> dict:
        state = self._read()
        articles = state.get("articles", {})
        pending = [pair for pair in ("self-owned/ja", "self-owned/en") if articles.get(pair, {}).get("status") != "live"]
        return {
            "status": "complete" if articles and not pending else "pending",
            "run_id": state.get("run_id"),
            "pending_pairs": pending,
        }

    def record_live(self, contract: dict, receipt: dict) -> dict:
        pair = f"self-owned/{contract['lang']}"
        with self._lock():
            state = self._read()
            entry = state.get("articles", {}).get(pair)
            if not entry or entry.get("artifact_sha256") != contract.get("source_sha256"):
                raise SelfOwnedInvariant("public receipt has no matching durable intent")
            expected_receipt = {
                "verified": True,
                "platform": "self-owned",
                "lang": contract["lang"],
                "artifact_id": contract["artifact_id"],
                "artifact_sha256": contract["source_sha256"],
                "preview_sha256": contract["preview_sha256"],
                "paid_sha256": contract["paid_sha256"],
                "public_id": contract["slug"],
            }
            if any(receipt.get(key) != value for key, value in expected_receipt.items()):
                raise SelfOwnedInvariant("public receipt differs from frozen contract")
            live = urlparse(str(receipt.get("live_url", "")))
            if (
                live.scheme != "https" or live.hostname != "aniccaai.com"
                or live.path != f"/blog/{contract['slug']}"
            ):
                raise SelfOwnedInvariant("public receipt URL is invalid")
            if entry.get("status") == "live":
                if entry.get("receipt") != receipt:
                    raise SelfOwnedInvariant("public receipt conflicts with prior reality")
                self._ensure_ledger_row(state, contract, receipt)
                return dict(entry)
            self._ensure_ledger_row(state, contract, receipt)
            entry["status"] = "live"
            entry["receipt"] = receipt
            _atomic_json(self.state_path, state)
            return dict(entry)

    def _ensure_ledger_row(self, state: dict, contract: dict, receipt: dict) -> None:
        rows = []
        if self.ledger_path.exists():
            for line in self.ledger_path.read_text(encoding="utf-8").splitlines():
                try:
                    value = json.loads(line)
                except (TypeError, json.JSONDecodeError):
                    continue
                if (
                    isinstance(value, dict)
                    and value.get("run_id") == state["run_id"]
                    and value.get("platform") == "self-owned"
                    and value.get("lang") == contract["lang"]
                    and value.get("published") is True
                ):
                    rows.append(value)
        if rows:
            if len(rows) != 1 or any(
                rows[0].get(key) != receipt.get(key)
                for key in (
                    "live_url", "artifact_id", "artifact_sha256",
                    "preview_sha256", "paid_sha256",
                )
            ):
                raise SelfOwnedInvariant("self-owned ledger conflicts with public receipt")
            return
        row = {
            "ts": receipt["observed_at"],
            "run_id": state["run_id"],
            "topic_id": state["topic_id"],
            "topic": state["topic_id"],
            "platform": "self-owned",
            "lang": contract["lang"],
            "state": "live",
            "published": True,
            "verified_logged_in": False,
            "reality_gate": "PASS",
            **receipt,
        }
        self.ledger_path.parent.mkdir(parents=True, exist_ok=True)
        with self.ledger_path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
            handle.flush()
            os.fsync(handle.fileno())

    def record_delivery(self, *, commit: str, remote: str, branch: str) -> None:
        if re.fullmatch(r"[0-9a-f]{40,64}", commit) is None:
            raise SelfOwnedInvariant("landing commit is invalid")
        with self._lock():
            state = self._read()
            delivery = {"commit": commit, "remote": remote, "branch": branch}
            prior = state.get("delivery")
            if prior is not None and prior != delivery:
                raise SelfOwnedInvariant("landing delivery conflicts with prior push")
            state["delivery"] = delivery
            _atomic_json(self.state_path, state)


def contracts_from_publication_state(publication_state_path: Path) -> list[dict]:
    try:
        state = json.loads(Path(publication_state_path).read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise SelfOwnedInvariant("base publication state is unreadable") from error
    contracts = []
    for lang in ("ja", "en"):
        path = Path(str(state.get("drafts", {}).get(lang, {}).get("path", "")))
        try:
            markdown = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as error:
            raise SelfOwnedInvariant("frozen draft cannot be read") from error
        contracts.append(build_contract(
            run_id=str(state.get("run_id", "")), lang=lang, markdown=markdown,
        ))
    return contracts


def _expected_paths(contracts: list[dict]) -> list[str]:
    return [
        str(Path("apps/landing/private/writer-articles") / f"{item['slug']}.json")
        for item in contracts
    ] + [str(REGISTRY_RELATIVE)]


def _targets_already_materialized(root: Path, contracts: list[dict]) -> bool:
    expected = set(_expected_paths(contracts))
    dirty = {
        line[3:]
        for line in _git(root, "status", "--porcelain", "--untracked-files=all").splitlines()
        if len(line) >= 4
    }
    if not dirty or not dirty <= expected:
        return False
    for contract in contracts:
        target = root / "apps/landing/private/writer-articles" / f"{contract['slug']}.json"
        try:
            if json.loads(target.read_text(encoding="utf-8")) != contract:
                return False
        except (OSError, UnicodeError, json.JSONDecodeError):
            return False
    try:
        registry = (root / REGISTRY_RELATIVE).read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return False
    if registry != _registry_source(_all_contract_slugs(root, [])):
        return False
    return True


def resume_publication(
    *, publication_state_path: Path, ledger_path: Path, landing_root: Path,
    remote: str, branch: str, base_url: str = "https://aniccaai.com",
    fetch_markup=None,
) -> dict:
    """Advance intent -> exact git delivery -> public readback by one safe tick."""
    publication_state_path = Path(publication_state_path)
    landing_root = Path(landing_root).resolve()
    state_path = publication_state_path.with_name("self-owned-publication.json")
    store = SelfOwnedPublicationStore(state_path, Path(ledger_path))
    contracts = contracts_from_publication_state(publication_state_path)
    store.prepare(publication_state_path, contracts)
    if store.plan()["status"] == "complete":
        return {"status": "complete", "run_id": contracts[0]["run_id"]}

    state = store._read()
    delivery = state.get("delivery")
    if not delivery:
        status = _git(landing_root, "status", "--porcelain", "--untracked-files=all")
        if status and not _targets_already_materialized(landing_root, contracts):
            return {"status": "deferred", "reason": "landing-worktree-dirty"}
        if not status:
            staged = stage_contracts(landing_root, contracts)
        else:
            staged = [
                {"status": "staged", "relative_path": path}
                for path in _expected_paths(contracts)
            ]
        changed_paths = [
            item["relative_path"] for item in staged if item["status"] == "staged"
        ]
        if changed_paths:
            result = commit_contract(
                landing_root, changed_paths,
                message=f"feat(writer): publish self-owned {contracts[0]['run_id']}",
                remote=remote, branch=branch,
            )
            commit = result["commit"]
        else:
            commit = _git(landing_root, "rev-parse", "HEAD")
            _git(landing_root, "push", remote, f"HEAD:refs/heads/{branch}")
        store.record_delivery(commit=commit, remote=remote, branch=branch)

    fetch = fetch_markup
    if fetch is None:
        def fetch(url: str) -> str:
            request = urllib.request.Request(url, headers={"User-Agent": "Writer-Agent/1.0"})
            with urllib.request.urlopen(request, timeout=8) as response:
                return response.read().decode("utf-8")
    waiting = []
    for contract in contracts:
        pair = f"self-owned/{contract['lang']}"
        if store._read()["articles"][pair].get("status") == "live":
            continue
        live_url = f"{base_url.rstrip('/')}/blog/{contract['slug']}"
        try:
            markup = fetch(live_url)
            receipt = verify_public_readback(
                contract, live_url, markup,
                observed_at=datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            )
        except Exception as error:  # deploy propagation is retried on the next tick
            waiting.append({"pair": pair, "reason": type(error).__name__})
            continue
        store.record_live(contract, receipt)
    plan = store.plan()
    return {
        "status": plan["status"],
        "run_id": plan["run_id"],
        "pending_pairs": plan["pending_pairs"],
        "waiting": waiting,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    resume = sub.add_parser("resume")
    resume.add_argument("--publication-state", required=True, type=Path)
    resume.add_argument("--ledger", required=True, type=Path)
    resume.add_argument("--landing-root", required=True, type=Path)
    resume.add_argument("--remote", required=True)
    resume.add_argument("--branch", required=True)
    resume.add_argument("--base-url", default="https://aniccaai.com")
    args = parser.parse_args()
    if args.command == "resume":
        result = resume_publication(
            publication_state_path=args.publication_state,
            ledger_path=args.ledger,
            landing_root=args.landing_root,
            remote=args.remote,
            branch=args.branch,
            base_url=args.base_url,
        )
        print(json.dumps(result, ensure_ascii=False, separators=(",", ":")))
    return 0


def commit_contract(
    landing_root: Path,
    relative_paths: list[str],
    *,
    message: str,
    remote: str | None = None,
    branch: str | None = None,
) -> dict:
    root = Path(landing_root).resolve()
    allowed: set[str] = set()
    for raw in relative_paths:
        path = Path(raw)
        is_contract = (
            path.parent == Path("apps/landing/private/writer-articles")
            and path.suffix == ".json"
        )
        is_registry = path == REGISTRY_RELATIVE
        if (
            path.is_absolute()
            or ".." in path.parts
            or not (is_contract or is_registry)
        ):
            raise SelfOwnedInvariant("publication target is outside the exact directory")
        allowed.add(path.as_posix())
    if not allowed or not message.strip():
        raise SelfOwnedInvariant("exact targets and commit message are required")
    dirty_lines = _git(root, "status", "--porcelain", "--untracked-files=all").splitlines()
    dirty = {line[3:] for line in dirty_lines if len(line) >= 4}
    if dirty != allowed:
        raise SelfOwnedInvariant("unrelated landing change appeared before commit")
    _git(root, "add", "--", *sorted(allowed))
    cached = set(_git(root, "diff", "--cached", "--name-only").splitlines())
    if cached != allowed:
        raise SelfOwnedInvariant("git index contains a non-publication target")
    _git(root, "commit", "-m", message)
    commit = _git(root, "rev-parse", "HEAD")
    if remote or branch:
        if not remote or not branch or re.fullmatch(r"[A-Za-z0-9._/-]+", branch) is None:
            raise SelfOwnedInvariant("push remote and branch must both be valid")
        _git(root, "push", remote, f"HEAD:refs/heads/{branch}")
    return {"commit": commit, "paths": sorted(allowed), "pushed": bool(remote)}


def public_receipt_markup(contract: dict) -> str:
    visible = {key: value for key, value in contract.items() if key != "paid_markdown"}
    payload = html.escape(json.dumps(visible, ensure_ascii=False, separators=(",", ":")))
    return (
        '<script id="writer-public-contract" type="application/json">'
        f"{payload}</script><main>{html.escape(contract['preview_markdown'])}</main>"
    )


def verify_public_readback(
    contract: dict, live_url: str, markup: str, *, observed_at: str,
) -> dict:
    parsed = urlparse(live_url)
    if parsed.scheme != "https" or parsed.hostname != "aniccaai.com" or parsed.path != f"/blog/{contract['slug']}":
        raise SelfOwnedInvariant("public URL does not match stable slug")
    try:
        observed = datetime.fromisoformat(observed_at.replace("Z", "+00:00"))
    except (AttributeError, ValueError) as error:
        raise SelfOwnedInvariant("observed_at is invalid") from error
    if observed.tzinfo is None:
        raise SelfOwnedInvariant("observed_at requires timezone")
    match = re.search(
        r'<script id="writer-public-contract" type="application/json">(.*?)</script>',
        markup,
        re.DOTALL,
    )
    if not match:
        raise SelfOwnedInvariant("public contract metadata is absent")
    try:
        public = json.loads(html.unescape(match.group(1)))
    except json.JSONDecodeError as error:
        raise SelfOwnedInvariant("public contract metadata is malformed") from error
    expected = {key: value for key, value in contract.items() if key != "paid_markdown"}
    if public != expected:
        raise SelfOwnedInvariant("public contract metadata differs from frozen artifact")
    visible_markup = re.sub(
        r'<script id="writer-public-contract" type="application/json">.*?</script>',
        "", html.unescape(markup), flags=re.DOTALL,
    )
    preview_probe = ""
    for line in contract["preview_markdown"].splitlines():
        candidate = re.sub(r"^[#>*_`~-]+\s*", "", line).strip()
        candidate = re.sub(r"\[([^]]+)\]\([^)]+\)", r"\1", candidate)
        if len(candidate) >= 20:
            preview_probe = candidate
            break
    if not preview_probe or preview_probe not in visible_markup:
        raise SelfOwnedInvariant("public preview is absent")
    paid_probe = ""
    for line in contract["paid_markdown"].splitlines():
        candidate = re.sub(r"^[#>*_`~-]+\s*", "", line).strip()
        candidate = re.sub(r"\[([^]]+)\]\([^)]+\)", r"\1", candidate)
        if len(candidate) >= 20:
            paid_probe = candidate
            break
    if contract["paid_markdown"] in html.unescape(markup) or (
        paid_probe and paid_probe in visible_markup
    ):
        raise SelfOwnedInvariant("paid body leaked into public response")
    return {
        "verified": True,
        "platform": "self-owned",
        "lang": contract["lang"],
        "artifact_id": contract["artifact_id"],
        "artifact_sha256": contract["source_sha256"],
        "preview_sha256": contract["preview_sha256"],
        "paid_sha256": contract["paid_sha256"],
        "live_url": live_url,
        "public_id": contract["slug"],
        "observed_at": observed_at,
    }


if __name__ == "__main__":
    raise SystemExit(main())
